---
name: Run Tests
on:
  push:
    branches: [ "main-1x" ]
  workflow_dispatch: 
jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    container: fedora:38
    strategy:
      matrix:
        version: ['12.x','16.x', '20.x', '24.x']
    steps:
      - run: | 
          dnf install libgpiod libgpiod-devel libgpiod-utils \
            nodejs-devel make g++ kmod kernel-modules-core -y
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm ci
          npm run build
          # npm run configure-gpio-sim
          # npm run test:coverage # unable to run in the simulator
