---
name: Publish npm package
on:
  push:
    tags:
      - '*'
permissions:
  id-token: write
  contents: read
env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt-get install gpiod libgpiod2 libgpiod-dev libnode-dev -y
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm ci
          npm run build
          npm publish --provenance --access public
